### PR TITLE
Added text for issue 17

### PR DESCRIPTION
**Pull request by MaximProshin**
Please review!

### CODE REVIEW

**Comment by tuexen** [comment]
I have an issue here: I would like to make clear, how the `cwnd` is used. I think it should limit what the sender can send and should take into account the DATA chunk headers. There is a difference between sending a single user message of 1000 bytes  or sending 1000 user messages of 1 byte.

Questions:
1. Do we agree an this?
2. Does this need to be address in the text under consideration in the issue?

**Comment by MaximProshin** [comment]
This is a good point and I think I agree but with some comments:
- I would rather update "outstanding data" description
- I would also correct the following statement in the RFC:
  
  B) At any given time, the sender MUST NOT transmit new data to a
    given transport address if it has cwnd or more bytes of data
    outstanding to that transport address.

=>

   B) At any given time, the sender MUST NOT transmit new data to a
      given transport address if it has cwnd or more bytes of
     *\* outstanding data **to that transport address. 

What do you think?

**Comment by tuexen** [comment]
Yepp. Can you update the pull request?

**Comment by MaximProshin** [comment]
Yes, I'll do it.

**Comment by MaximProshin** [comment]
By the way, there are many places where "data outstanding" not only "outstanding data" is used. I still think it would be good to correct it but since there are many places to correct, probably it is better to fix it just in the terminology, e.g. 
o  Outstanding data (or Data outstanding or Data in flight): The total amount ...

What do you think?

**Comment by MaximProshin** [comment]
Here is the corrected variant:
https://github.com/sctplab/rfc4960bis/pull/43/commits/30bcf9e5a6e02b138f99583df65d364c7a67c46a

**Comment by tuexen** [comment]
My browser finds 37 instances of `outstanding`. I think it might be worth going through them and use consistent terminology. I think Karen shared that opinion, but I'm not sure...

**Comment by MaximProshin** [comment]
Updated according to our discussion in IETF96. I hope it is the final variant.
Please check and merge.

**Review by tuexen — APPROVED** [review]

**Comment by tuexen** [comment]
Manually merged in https://github.com/sctplab/rfc4960bis/commit/a519d2897e4168f3b3e6defcca74fdc407666a8f.

**Pull request closed without merging**
